### ISSUE TITLE
linux Mint19 can not run sh run.sh

### ISSUE THREAD

**Issue by dragon220321** [acely/Arctime-Pro#12]
OS:Linux Mint 19.3 Cinnamon
Java: openjdk version "11.0.4" 2019-07-16
vlc:3.0.8
arctime-pro:2.3

can not run sh run.sh

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bulenkov.darcula.DarculaLaf (file:/home/user01/ARCTIME_PRO_2.3_LINUX/ArcTime_lib/darcula.jar) to field javax.swing.text.html.HTMLEditorKit.DEFAULT_STYLES_KEY
WARNING: Please consider reporting this to the maintainers of com.bulenkov.darcula.DarculaLaf
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/awt/AWTUtilities$Translucency
	at org.arctime.main.ArcTime.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.awt.AWTUtilities$Translucency
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

**Comment by dragon220321** [comment]
It works well now.
 
When I change Java version from Java11 to Java8 and it works well.It is Incompatible with java11.

sudo apt install openjdk-8-jdk

sudo update-alternatives --config java

**Comment by dragon220321** [comment]
It still can not work well on Linux Mint 19.3 Cinnamon.Maybe it can not detect VLC on my mint OS.
The error log:
Exception in thread "Thread-3" java.lang.NullPointerException
	at uk.co.caprica.vlcj.factory.discovery.strategy.BaseNativeDiscoveryStrategy.discover(BaseNativeDiscoveryStrategy.java:68)
	at uk.co.caprica.vlcj.factory.discovery.NativeDiscovery.discover(NativeDiscovery.java:112)
	at org.arctime.main.p.run(Unknown Source)

I have added vlc path to ./tools/config/vlcpath.txt , and have tried reinstall VLC, but it didn't work.
Now I use arctime on windows platform.So delicious！

**Comment by acely** [comment]
@dragon220321 Yes, it's currently not compatable with java 9 or later version, it's only compatable with java 8.
I've already fixed the vlc loading problem, the fix will come with arctime 2.4.1 release.
Thanks for your infomations!

**Comment by acely** [comment]
Duplicate of #16
